# Generated by Django 2.1.4 on 2019-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='graduation_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
