# Generated by Django 2.1.4 on 2019-04-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0002_auto_20190410_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledetail',
            name='headshot',
            field=models.ImageField(default='personimage/default.png', upload_to='personimage'),
        ),
    ]
