from django.db import models
# Create your models here.
class Tsetse(models.Model):
	caseno2 = models.CharField(max_length=50,null=True, blank=True)
	vpn  = models.CharField(max_length=50,null=True, blank=True)
	volume  = models.CharField(max_length=50,null=True, blank=True)
	page	 = models.CharField(max_length=50,null=True, blank=True)
	number_on_page	 = models.CharField(max_length=50,null=True, blank=True)
	capture_day_of_month	 = models.CharField(max_length=50,null=True, blank=True)
	capture_month_year	 = models.CharField(max_length=50,null=True, blank=True)
	capture_year	 = models.CharField(max_length=50,null=True, blank=True)
	experimental_month	 = models.CharField(max_length=50,null=True, blank=True)
	capture_days_since_01011960 = models.CharField(max_length=50,null=True, blank=True)
	disector_code = models.CharField(max_length=50,null=True, blank=True)
	microscope = models.CharField(max_length=50,null=True, blank=True)
	capture_sites = models.CharField(max_length=50,null=True, blank=True)
	capture_method_code = models.CharField(max_length=50,null=True, blank=True)
	capture_start_time = models.CharField(max_length=50,null=True, blank=True)
	capture_end_time = models.CharField(max_length=50,null=True, blank=True)
	dissection_day = models.CharField(max_length=50,null=True, blank=True)
	dissection_month = models.CharField(max_length=50,null=True, blank=True)
	time_of_disection_am_or_pm = models.CharField(max_length=50,null=True, blank=True)
	genus= models.CharField(max_length=50,null=True, blank=True)
	sex= models.CharField(max_length=50,null=True, blank=True)
	largest_ooctye_length_mm_x100= models.CharField(max_length=50,null=True, blank=True)
	largest_ooctye_diameter_mm_x100 = models.CharField(max_length=50,null=True, blank=True)
	second_largest_ooctye_length_mm_x100 = models.CharField(max_length=50,null=True, blank=True)
	ovarian_category = models.CharField(max_length=50,null=True, blank=True)
	uterine_content = models.CharField(max_length=50,null=True, blank=True)
	uterine_length_ulm_mm_x100= models.CharField(max_length=50,null=True, blank=True)
	uterine_length_udm_mm_x100= models.CharField(max_length=50,null=True, blank=True)
	left_spermatophore_content_0_to_10= models.CharField(max_length=50,null=True, blank=True)
	right_spermatophore_content_0_to_10= models.CharField(max_length=50,null=True, blank=True)
	hunger_stage = models.CharField(max_length=50,null=True, blank=True)
	wing_length_scale_wl = models.CharField(max_length=50,null=True, blank=True)
	wing_length_mm_x100_wlm = models.CharField(max_length=50,null=True, blank=True)
	facwlmnew = models.CharField(max_length=50,null=True, blank=True)
	wing_length_mm_x100_wlm2 = models.CharField(max_length=50,null=True, blank=True)
	wing_fray_1_to_6= models.CharField(max_length=50,null=True, blank=True)
	determinant_for_pregnancy_stage = models.CharField(max_length=50,null=True, blank=True)
	percent_pregnancy_completed = models.CharField(max_length=50,null=True, blank=True)
	inter_larval_period= models.CharField(max_length=50,null=True, blank=True)
	estimated_day_of_pregnancy= models.CharField(max_length=50,null=True, blank=True)
	estimated_age_days= models.CharField(max_length=50,null=True, blank=True)
	estimated_birth_day_julian= models.CharField(max_length=50,null=True, blank=True)
	cut_off_al_length_for_deciding_if_fly_aborted= models.CharField(max_length=50,null=True, blank=True)
	error_code_1 = models.CharField(max_length=50,null=True, blank=True)
	error_code_2 = models.CharField(max_length=50,null=True, blank=True)
	r_is_1_if_disector_noted_a_problem_r_is_0_otherwise = models.CharField(max_length=50,null=True, blank=True)
	tube_number= models.CharField(max_length=50,null=True, blank=True)
	alphanumeric_label_for_tube= models.CharField(max_length=50,null=True, blank=True)
	pteridine= models.CharField(max_length=50,null=True, blank=True)
	mother_thorasic_residue_dry_weight= models.CharField(max_length=50,null=True, blank=True)
	mark= models.CharField(max_length=50,null=True, blank=True)
	uterine_volume = models.CharField(max_length=50,null=True, blank=True)
	dwu= models.CharField(max_length=50,null=True, blank=True)
	rdwu= models.CharField(max_length=50,null=True, blank=True)
	fatu= models.CharField(max_length=50,null=True, blank=True)
	fwu= models.CharField(max_length=50,null=True, blank=True)
	tr= models.CharField(max_length=50,null=True, blank=True)
	mothers_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_resid_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_fat_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_abdominal_resid_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_haematin = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_resid_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_fat_weight= models.CharField(max_length=50,null=True, blank=True)
	uterine_dry_weight_est_from_volume= models.CharField(max_length=50,null=True, blank=True)
	uterine_resid_dry_weight_est_from_volume= models.CharField(max_length=50,null=True, blank=True)
	uterine_fat_weight_est_from_volume = models.CharField(max_length=50,null=True, blank=True)
	uterine_fresh_weight_est_from_volume = models.CharField(max_length=50,null=True, blank=True)
	puparial_length_mm_x100_lpm= models.CharField(max_length=50,null=True, blank=True)
	puparial_length_mm_x100_dpm= models.CharField(max_length=50,null=True, blank=True)
	uterine_volume_volp= models.CharField(max_length=50,null=True, blank=True)
	puparial_dry_weight_dwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_resid_dry_weight_rdwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_fatp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_corrected_for_process_delay_fatp0= models.CharField(max_length=50,null=True, blank=True)
	puparial_fresh_weight_fwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_dry_weight_est_from_volume_edwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_resid_dry_weight_est_from_volume_erdwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_est_from_volume_efatp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fresh_weight_est_from_volume_efwp= models.CharField(max_length=50,null=True, blank=True)
	fd= models.CharField(max_length=50,null=True, blank=True)
	fjd= models.CharField(max_length=50,null=True, blank=True)
	idd= models.CharField(max_length=50,null=True, blank=True)# column name to be reviewd
	im= models.CharField(max_length=50,null=True, blank=True)
	ijd= models.CharField(max_length=50,null=True, blank=True)
	ep= models.CharField(max_length=50,null=True, blank=True)
	presence_of_adult_mx= models.CharField(max_length=50,null=True, blank=True)
	presence_of_pupa_px= models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_totfat0= models.CharField(max_length=50,null=True, blank=True)
	estimated_mother_plus_pupa_dry_weight_etotdw = models.CharField(max_length=50,null=True, blank=True)
	estimated_mother_plus_pupa_resid_dry_weight_etotrdw = models.CharField(max_length=50,null=True, blank=True)
	estimated_mother_plus_pupa_fat_weight_etotfat= models.CharField(max_length=50,null=True, blank=True)
	bt= models.CharField(max_length=50,null=True, blank=True)
	capture_month_of_experiment_cms= models.CharField(max_length=50,null=True, blank=True)
	birth_month_different_definition_from_bm_bm2= models.CharField(max_length=50,null=True, blank=True)
	birth_month_bm= models.CharField(max_length=50,null=True, blank=True)
	birth_year_by= models.CharField(max_length=50,null=True, blank=True)
	birth_month_for_female_born_in_month_cms_bms= models.CharField(max_length=50,null=True, blank=True)
	pooled_capture_sites_sitep= models.CharField(max_length=50,null=True, blank=True)
	pooled_capture_methods_mdp= models.CharField(max_length=50,null=True, blank=True)
	estimated_age_negative_changed_to_0_age0= models.CharField(max_length=50,null=True, blank=True)
	year_of_dissection_dy= models.CharField(max_length=50,null=True, blank=True)
	days_delay_in_dissection_del= models.CharField(max_length=50,null=True, blank=True)
	sperm_left_plus_right_slr = models.CharField(max_length=50,null=True, blank=True)
	total_sperm_pooled_units_4_slrp= models.CharField(max_length=50,null=True, blank=True)
	total_sperm_pooled_0_1to8_9to16_17to20 = models.CharField(max_length=50,null=True, blank=True)
	day_of_the_year_dofy = models.CharField(max_length=50,null=True, blank=True)
	day_of_the_year_9_day_pool_dofy9 = models.CharField(max_length=50,null=True, blank=True)
	pyriproxyfen_traps_or_targets_used_pyri = models.CharField(max_length=50,null=True, blank=True)
	methods_pooled_major_mdpall = models.CharField(max_length=50,null=True, blank=True)
	log_10_of_haematin_in_nanograms_log10hm = models.CharField(max_length=50,null=True, blank=True)
	ovcat_where_ppp_files_with_u_0_put_into_next_ovcat_cnu = models.CharField(max_length=50,null=True, blank=True)
	full_term_ppp_pregnant_etc_ftpp = models.CharField(max_length=50,null=True, blank=True)
	full_term_ppp_pregnant_etc_ftppp = models.CharField(max_length=50,null=True, blank=True)
	full_term_ppp_pregnant_etc_ppall= models.CharField(max_length=50,null=True, blank=True)
	pprpl= models.CharField(max_length=50,null=True, blank=True)
	pprpl2= models.CharField(max_length=50,null=True, blank=True)
	runmin9= models.CharField(max_length=50,null=True, blank=True)
	mothers_dry_weight_mg_dwmg= models.CharField(max_length=50,null=True, blank=True)
	residual_dry_weight_mg_rdwmg= models.CharField(max_length=50,null=True, blank=True)
	mothers_fat_weight_mg_fatmg = models.CharField(max_length=50,null=True, blank=True)
	mothers_thoracic_resid_dry_weight_mg_trdwmg = models.CharField(max_length=50,null=True, blank=True)
	mothers_abdominal_resid_dry_weight_mg_ardwmg = models.CharField(max_length=50,null=True, blank=True)
	wing_length_wlmm = models.CharField(max_length=50,null=True, blank=True)
	puparial_fresh_weight_mg_fwpmg = models.CharField(max_length=50,null=True, blank=True)
	puparial_dry_weight_mg_dwpmg = models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_mg_fatpmg = models.CharField(max_length=50,null=True, blank=True)
	puparial_resid_dry_weight_mg_rdwpmg = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_dry_weight_mg_totdwmg = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_resid_dry_weight_mg_totrdwmg = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_fat_weight_mg_totfatmg = models.CharField(max_length=50,null=True, blank=True)
	#Column datat types followed
	ctemp = models.CharField(max_length=50,null=True, blank=True)# column name to be reviewd
	cf56 = models.CharField(max_length=50,null=True, blank=True)# column name to be reviewd
	cf6= models.CharField(max_length=50,null=True, blank=True) 
	testtem = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	date_sample_started_datest= models.CharField(max_length=50,null=True, blank=True)
	capture_month_of_year_cctem= models.CharField(max_length=50,null=True, blank=True)
	newpage_numbering_pgall= models.CharField(max_length=50,null=True, blank=True)
	unique_number_for_each_fly_in_file_idfly= models.CharField(max_length=50,null=True, blank=True)
	date_sample_collected_datecap =models.DateField(null=True, blank=True)
	datedis = models.DateField(null=True, blank=True)
	ndvi = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi90 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi91 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi92 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi93 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi94 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi300 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi301 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi302 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	ndvi303 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	tmax = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmax90 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmax91 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmax92 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmax93 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmax94 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmin = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmin90 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmin91 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmin92 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmin93 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tmin94 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True)
	tbar = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)
	tbar90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)
	tbar91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)
	tbar92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)
	tbar93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)
	tbar94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)
	rain = models.DecimalField(max_digits= 6, decimal_places=3, null=True, blank=True)
	
	cf456 = models.IntegerField(null=True, blank=True, verbose_name=('Ovarian category where flies recategorised if f>3'))
	dur = models.IntegerField(null=True, blank=True)
	tbars = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Average temperature Capture day Sensor'))
	tbars90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('tbars over 9-day forward from capture day'))
	tbars91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward from capture day'))
	tbars92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward, starting 9-days prior to capture day'))
	tbars93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward, starting 18-days prior to capture day'))
	tbars94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward, starting 27-days prior to capture day'))
	rhbars = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Average relative humidity on Capture day Sensor'))
	rhbars90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('rhbars over 9-day forward from capture day'))
	rhbars91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('rhbars over 9-day backward from capture day'))
	rhbars92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('rhbars over 9-day backward, starting 9-days prior to capture day'))
	rhbars93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('rhbars over 9-day backward, starting 18-days prior to capture day'))
	rhbars94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('rhbars over 9-day backward, starting 27-days prior to capture day'))
	sdhgbars = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('Average Saturation deficit mmHg on Capture day Sensor'))
	sdhgbars90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('sdhgbars over 9-day forward from capture day'))
	sdhgbars91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('sdhgbars over 9-day backward from capture day'))
	sdhgbars92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('sdhgbars over 9-day backward, starting 9-days prior to capture day'))
	sdhgbars93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('sdhgbars over 9-day backward, starting 18-days prior to capture day'))
	sdhgbars94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('sdhgbars over 9-day backward, starting 27-days prior to capture day'))

	hmmug = models.CharField(max_length=50,null=True, blank=True,  verbose_name=('Haeamtin content not sure of units'))
	dj= models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('Day of experiment rescaled'))
	nf = models.IntegerField(null=True, blank=True,  verbose_name=('Dissected for infection at all 0/1'))
	la = models.CharField(max_length=50,null=True, blank=True, verbose_name=('Infection code for labrum'))
	hp = models.CharField(max_length=50,null=True, blank=True, verbose_name=('Infection code for hypopharynx'))
	sg = models.CharField(max_length=50,null=True, blank=True, verbose_name=('Infection code for salivary glands'))
	mg = models.CharField(max_length=50,null=True, blank=True,  verbose_name=('Infection code for midgut'))
	la2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for labrum'))
	hp2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for hypopharynx'))
	mpart = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for any mouthpart tryps'))
	mg2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for midgut'))
	vivax = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for vivax'))
	sg2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for salivary glands'))
	congo = models.IntegerField(null=True, blank=True, verbose_name=('Infection 0/1 for congo'))
	brucei = models.IntegerField(null=True, blank=True, verbose_name=('Infection 0/1 for brucei'))
	brucong = models.IntegerField(null=True, blank=True, verbose_name=('Infection 0/1 for mixed congo/brucei'))
	fatppcg= models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Measured percent fat in pupa: fatp/dwp'))
	efatp2 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Pupal fat estimated as 32% of pupal dry weight'))
	etotfat2 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Mother fat + pupal fat as 32% of DWP'))
	eggooc = models.IntegerField(null=True, blank=True, verbose_name=('Egg or oocyte length for flies in ftpp 16 or 17'))
	abort = models.IntegerField(null=True, blank=True, verbose_name=('Abort=1 if e1=31-33 0 otherwise'))
	tbar91p = models.IntegerField(null=True, blank=True, verbose_name=('Pooled running mean prev 9-days'))
	cm2 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True , verbose_name=('Fortnightly time intervals'))
	umt = models.IntegerField(null=True, blank=True, verbose_name=('Equals 1 if uterus empty, zero if full'))
	tbar91sq = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True , verbose_name=('Quadratic (tbar91^2)/30'))
	fatppcprdw = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Measured pupal fat as percent of pupal RDW'))
	fatpcrdw =models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('Maternal postpartum fat divided by RDW'))
	propfat = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Pupal fat as proportion of total fat: efatp2/etotfat2'))
	fatproptrdw = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Maternal postpartum fat divided by TRDW'))
	fatranspc = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Percent of mothers fat transfered to pupa'))
	etotfat2sq = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('etotfat2 squared') )
	date = models.DateField(null=True, blank=True)
	windv = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Wind velocity m/s'))
	windv9 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Wind vel average over prior 9 days'))
	soiltem = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Soil temp degrees C'))
	soiltem9 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Soil temp average over prior 9days'))
	radiation = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Black body radiation degrees C'))
	rad9 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Black body radiation average over prior 9 days'))
	bday9 = models.IntegerField(null=True, blank=True,verbose_name=('Birthday in 9 day groups'))
	bdaydate = models.DateField(null=True, blank=True, verbose_name=('Birthday formatted as date'))
	bmon = models.IntegerField(null=True, blank=True, verbose_name=('Month of the year fly emerged as teneral'))
	wlmpl = models.IntegerField(null=True, blank=True)
	nfmmg = models.IntegerField(null=True, blank=True, verbose_name=('Mouthparts & midgut BOTH dissected for infection'))
	fsq = models.IntegerField(null=True, blank=True)
	cnusq2 = models.IntegerField(null=True, blank=True,verbose_name=('cnu squared NEW verison Dec 2017'))
	tbarm0 = models.CharField(max_length=50,null=True, blank=True)
	tbarm1 = models.CharField(max_length=50,null=True, blank=True)
	tbarm2 = models.CharField(max_length=50,null=True, blank=True)
	rhm0 = models.CharField(max_length=50,null=True, blank=True)
	rhm1 = models.CharField(max_length=50,null=True, blank=True)
	rhm2 = models.CharField(max_length=50,null=True, blank=True)
	sdefm0 = models.CharField(max_length=50,null=True, blank=True)
	sdefm1 = models.CharField(max_length=50,null=True, blank=True)
	sdefm2 = models.CharField(max_length=50,null=True, blank=True)
	mdpall2 = models.IntegerField(null=True, blank=True,verbose_name=('Methods max pooling nkl'))
	ptpl = models.IntegerField(null=True, blank=True)
	wlmnew = models.CharField(max_length=50,null=True, blank=True)
	facwlmold = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)


	class Meta:
		verbose_name_plural = "Tsetse data"
