from django.db import models
# Create your models here.
class Tsetse(models.Model):
	caseno2 = models.CharField(max_length=50,null=True, blank=True)
	vpn  = models.CharField(max_length=50,null=True, blank=True)
	volume  = models.CharField(max_length=50,null=True, blank=True)
	page	 = models.CharField(max_length=50,null=True, blank=True)
	number_on_page	 = models.CharField(max_length=50,null=True, blank=True)
	capture_day_of_month	 = models.CharField(max_length=50,null=True, blank=True)
	capture_month_year	 = models.CharField(max_length=50,null=True, blank=True)
	capture_year	 = models.CharField(max_length=50,null=True, blank=True)
	experimental_month	 = models.CharField(max_length=50,null=True, blank=True)
	capture_days_since_01011960 = models.CharField(max_length=50,null=True, blank=True)
	disector_code = models.CharField(max_length=50,null=True, blank=True)
	microscope = models.CharField(max_length=50,null=True, blank=True)
	capture_sites = models.CharField(max_length=50,null=True, blank=True)
	capture_method_code = models.CharField(max_length=50,null=True, blank=True)
	capture_start_time = models.CharField(max_length=50,null=True, blank=True)
	capture_end_time = models.CharField(max_length=50,null=True, blank=True)
	dissection_day = models.CharField(max_length=50,null=True, blank=True)
	dissection_month = models.CharField(max_length=50,null=True, blank=True)
	time_of_disection_am_or_pm = models.CharField(max_length=50,null=True, blank=True)
	genus= models.CharField(max_length=50,null=True, blank=True)
	sex= models.CharField(max_length=50,null=True, blank=True)
	largest_ooctye_length_mm_x100= models.CharField(max_length=50,null=True, blank=True)
	largest_ooctye_diameter_mm_x100 = models.CharField(max_length=50,null=True, blank=True)
	second_largest_ooctye_length_mm_x100 = models.CharField(max_length=50,null=True, blank=True)
	ovarian_category = models.CharField(max_length=50,null=True, blank=True)
	uterine_content = models.CharField(max_length=50,null=True, blank=True)
	uterine_length_ulm_mm_x100= models.CharField(max_length=50,null=True, blank=True)
	uterine_length_udm_mm_x100= models.CharField(max_length=50,null=True, blank=True)
	left_spermatophore_content_0_to_10= models.CharField(max_length=50,null=True, blank=True)
	right_spermatophore_content_0_to_10= models.CharField(max_length=50,null=True, blank=True)
	hunger_stage = models.CharField(max_length=50,null=True, blank=True)
	wing_length_scale_wl = models.CharField(max_length=50,null=True, blank=True)
	wing_length_mm_x100_wlm = models.CharField(max_length=50,null=True, blank=True)
	facwlmnew = models.CharField(max_length=50,null=True, blank=True)
	wing_length_mm_x100_wlm2 = models.CharField(max_length=50,null=True, blank=True)
	wing_fray_1_to_6= models.CharField(max_length=50,null=True, blank=True)
	determinant_for_pregnancy_stage = models.CharField(max_length=50,null=True, blank=True)
	percent_pregnancy_completed = models.CharField(max_length=50,null=True, blank=True)
	inter_larval_period= models.CharField(max_length=50,null=True, blank=True)
	estimated_day_of_pregnancy= models.CharField(max_length=50,null=True, blank=True)
	estimated_age_days= models.CharField(max_length=50,null=True, blank=True)
	estimated_birth_day_julian= models.CharField(max_length=50,null=True, blank=True)
	cut_off_al_length_for_deciding_if_fly_aborted= models.CharField(max_length=50,null=True, blank=True)
	error_code_1 = models.CharField(max_length=50,null=True, blank=True)
	error_code_2 = models.CharField(max_length=50,null=True, blank=True)
	r_is_1_if_disector_noted_a_problem_r_is_0_otherwise = models.CharField(max_length=50,null=True, blank=True)
	tube_number= models.CharField(max_length=50,null=True, blank=True)
	alphanumeric_label_for_tube= models.CharField(max_length=50,null=True, blank=True)
	pteridine= models.CharField(max_length=50,null=True, blank=True)
	mother_thorasic_residue_dry_weight= models.CharField(max_length=50,null=True, blank=True)
	mark= models.CharField(max_length=50,null=True, blank=True)
	uterine_volume = models.CharField(max_length=50,null=True, blank=True)
	dwu= models.CharField(max_length=50,null=True, blank=True)
	rdwu= models.CharField(max_length=50,null=True, blank=True)
	fatu= models.CharField(max_length=50,null=True, blank=True)
	fwu= models.CharField(max_length=50,null=True, blank=True)
	tr= models.CharField(max_length=50,null=True, blank=True)
	mothers_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_resid_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_fat_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_abdominal_resid_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mothers_haematin = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_resid_dry_weight = models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_fat_weight= models.CharField(max_length=50,null=True, blank=True)
	uterine_dry_weight_est_from_volume= models.CharField(max_length=50,null=True, blank=True)
	uterine_resid_dry_weight_est_from_volume= models.CharField(max_length=50,null=True, blank=True)
	uterine_fat_weight_est_from_volume = models.CharField(max_length=50,null=True, blank=True)
	uterine_fresh_weight_est_from_volume = models.CharField(max_length=50,null=True, blank=True)
	puparial_length_mm_x100_lpm= models.CharField(max_length=50,null=True, blank=True)
	puparial_length_mm_x100_dpm= models.CharField(max_length=50,null=True, blank=True)
	uterine_volume_volp= models.CharField(max_length=50,null=True, blank=True)
	puparial_dry_weight_dwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_resid_dry_weight_rdwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_fatp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_corrected_for_process_delay_fatp0= models.CharField(max_length=50,null=True, blank=True)
	puparial_fresh_weight_fwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_dry_weight_est_from_volume_edwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_resid_dry_weight_est_from_volume_erdwp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fat_weight_est_from_volume_efatp= models.CharField(max_length=50,null=True, blank=True)
	puparial_fresh_weight_est_from_volume_efwp= models.CharField(max_length=50,null=True, blank=True)
	fd= models.CharField(max_length=50,null=True, blank=True)
	fjd= models.CharField(max_length=50,null=True, blank=True)
	idd= models.CharField(max_length=50,null=True, blank=True)#modified column
	im= models.CharField(max_length=50,null=True, blank=True)
	ijd= models.CharField(max_length=50,null=True, blank=True)
	ep= models.CharField(max_length=50,null=True, blank=True)
	presence_of_adult_mx= models.CharField(max_length=50,null=True, blank=True)
	presence_of_pupa_px= models.CharField(max_length=50,null=True, blank=True)
	mother_plus_pupa_totfat0= models.CharField(max_length=50,null=True, blank=True)
	estimated_mother_plus_pupa_dry_weight_etotdw = models.CharField(max_length=50,null=True, blank=True)
	estimated_mother_plus_pupa_resid_dry_weight_etotrdw = models.CharField(max_length=50,null=True, blank=True)
	estimated_mother_plus_pupa_fat_weight_etotfat= models.CharField(max_length=50,null=True, blank=True)
	bt= models.CharField(max_length=50,null=True, blank=True)
	capture_month_of_experiment_cms= models.CharField(max_length=50,null=True, blank=True)
	birth_month_different_definition_from_bm_bm2= models.CharField(max_length=50,null=True, blank=True)
	birth_month_bm= models.CharField(max_length=50,null=True, blank=True)
	birth_year_by= models.CharField(max_length=50,null=True, blank=True)
	birth_month_for_female_born_in_month_cms_bms= models.CharField(max_length=50,null=True, blank=True)
	pooled_capture_sites_sitep= models.CharField(max_length=50,null=True, blank=True)
	pooled_capture_methods_mdp= models.CharField(max_length=50,null=True, blank=True)
	estimated_age_negative_changed_to_0_age0= models.CharField(max_length=50,null=True, blank=True)
	year_of_dissection_dy= models.CharField(max_length=50,null=True, blank=True)
	days_delay_in_dissection_del= models.CharField(max_length=50,null=True, blank=True)
	sperm_left_plus_right_slr = models.CharField(max_length=50,null=True, blank=True)
	total_sperm_pooled_units_4_slrp= models.CharField(max_length=50,null=True, blank=True)
	total_sperm_pooled_0_1to8_9to16_17to20 = models.CharField(max_length=50,null=True, blank=True)
	day_of_the_year_dofy = models.CharField(max_length=50,null=True, blank=True)
	day_of_the_year_9_day_pool_dofy9 = models.CharField(max_length=50,null=True, blank=True)
	pyriproxyfen_traps_or_targets_used_pyri = models.CharField(max_length=50,null=True, blank=True)
	methods_pooled_major_mdpall = models.CharField(max_length=50,null=True, blank=True)
	log_10_of_haematin_in_nanograms_log10hm = models.CharField(max_length=50,null=True, blank=True)
	ovcat_where_ppp_files_with_u_0_put_into_next_ovcat_cnu = models.CharField(max_length=50,null=True, blank=True)
	full_term_ppp_pregnant_etc_ftpp = models.CharField(max_length=50,null=True, blank=True)
	full_term_ppp_pregnant_etc_ftppp = models.CharField(max_length=50,null=True, blank=True)
	full_term_ppp_pregnant_etc_ppall= models.CharField(max_length=50,null=True, blank=True)
	pprpl= models.CharField(max_length=50,null=True, blank=True)
	pprpl2= models.CharField(max_length=50,null=True, blank=True)
	runmin9= models.CharField(max_length=50,null=True, blank=True)
	mothers_dry_weight_mg_dwmg= models.CharField(max_length=50,null=True, blank=True)
	residual_dry_weight_mg_rdwmg= models.CharField(max_length=50,null=True, blank=True)
	
	class Meta:
		verbose_name_plural = "Tsetse data"
