# Generated by Django 2.1.4 on 2019-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tsetse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseno2', models.CharField(blank=True, max_length=50, null=True)),
                ('vpn', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('number_on_page', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_day_of_month', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_month_year', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_year', models.CharField(blank=True, max_length=50, null=True)),
                ('experimental_month', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_days_since_01011960', models.CharField(blank=True, max_length=50, null=True)),
                ('disector_code', models.CharField(blank=True, max_length=50, null=True)),
                ('microscope', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_sites', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tsetse data',
            },
        ),
    ]
