# Generated by Django 2.1.4 on 2019-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0002_auto_20190426_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsetse',
            name='second_largest_ooctye_length_mm_x100',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
