# Generated by Django 2.1.4 on 2019-04-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0003_tsetse_second_largest_ooctye_length_mm_x100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsetse',
            old_name='inter_larval_perioed',
            new_name='inter_larval_period',
        ),
    ]
