# Generated by Django 2.1.4 on 2019-04-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0004_auto_20190426_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsetse',
            old_name='puparial_dry_weight_est_from_volume_erdwp',
            new_name='birth_month_bm',
        ),
        migrations.AddField(
            model_name='tsetse',
            name='birth_month_different_definition_from_bm_bm2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='birth_month_for_female_born_in_month_cms_bms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='birth_year_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='capture_month_of_experiment_cms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='day_of_the_year_9_day_pool_dofy9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='day_of_the_year_dofy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='days_delay_in_dissection_del',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='estimated_age_negative_changed_to_0_age0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='estimated_mother_plus_pupa_dry_weight_etotdw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='estimated_mother_plus_pupa_fat_weight_etotfat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='estimated_mother_plus_pupa_resid_dry_weight_etotrdw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fjd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='full_term_ppp_pregnant_etc_ftpp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='full_term_ppp_pregnant_etc_ftppp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='full_term_ppp_pregnant_etc_ppall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='idd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ijd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='im',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='log_10_of_haematin_in_nanograms_log10hm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='methods_pooled_major_mdpall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mother_plus_pupa_totfat0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mothers_dry_weight_mg_dwmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ovcat_where_ppp_files_with_u_0_put_into_next_ovcat_cnu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pooled_capture_methods_mdp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pooled_capture_sites_sitep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pprpl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pprpl2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='presence_of_adult_mx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='presence_of_pupa_px',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_dry_weight_est_from_volume_edwp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_fat_weight_est_from_volume_efatp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_fresh_weight_est_from_volume_efwp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_resid_dry_weight_est_from_volume_erdwp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pyriproxyfen_traps_or_targets_used_pyri',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='residual_dry_weight_mg_rdwmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='runmin9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sperm_left_plus_right_slr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='total_sperm_pooled_0_1to8_9to16_17to20',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='total_sperm_pooled_units_4_slrp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='year_of_dissection_dy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
