# Generated by Django 2.1.4 on 2019-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0005_auto_20190427_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsetse',
            name='mother_plus_pupa_dry_weight_mg_totdwmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mother_plus_pupa_fat_weight_mg_totfatmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mother_plus_pupa_resid_dry_weight_mg_totrdwmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mothers_abdominal_resid_dry_weight_mg_ardwmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mothers_fat_weight_mg_fatmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mothers_thoracic_resid_dry_weight_mg_trdwmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_dry_weight_mg_dwpmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_fat_weight_mg_fatpmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_fresh_weight_mg_fwpmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='puparial_resid_dry_weight_mg_rdwpmg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wing_length_wlmm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
