# Generated by Django 2.1.4 on 2019-04-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0006_auto_20190428_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsetse',
            name='capture_month_of_year_cctem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cf56',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cf6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ctemp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='date_sample_collected_datecap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='date_sample_started_datest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='datedis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi300',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi301',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi302',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi303',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi90',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi91',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi92',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi93',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ndvi94',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='newpage_numbering_pgall',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbar',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbar90',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbar91',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='testtem',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmax',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmax90',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmax91',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmax92',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmax93',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmax94',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmin',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmin90',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmin91',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmin92',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmin93',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tmin94',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='unique_number_for_each_fly_in_file_idfly',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
