# Generated by Django 2.1.4 on 2019-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0008_auto_20190430_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsetse',
            name='abort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bday9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bdaydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bmon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cm2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cnusq2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='day_of_experiment_dj',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dissected_for_infection_at_all_0_or_1_nf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='efatp2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='eggooc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='etotfat2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='etotfat2sq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='facwlmold',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatpcrdw',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatppcprdw',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatproptrdw',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatranspc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fsq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='hmmug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_any_mouthpart_tryps_mpart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_brucei_brucei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_congo_congo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_hypopharynx_hp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_labrum_la2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_midgut_mg2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_mixed_congo_or_brucei_brucong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_salivary_glands_sg2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_0_or_1_for_vivax_vivax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_code_for_hypopharynx_hp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_code_for_labrum_la',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_code_for_midgut_mg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='infection_code_for_salivary_glands_sg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mdpall2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='measured_percent_fat_in_pupa_fatppcg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='nfmmg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='propfat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ptpl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rad9',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='radiation',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rhm0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rhm1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rhm2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sdefm0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sdefm1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sdefm2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='soiltem',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='soiltem9',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbar91p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbar91sq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbarm0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbarm1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tbarm2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='umt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='windv',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='windv9',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wlmnew',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wlmpl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
